name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'dev'

model-paths: ["models"]

models:
  dbt_project:
    bronze:
      +materialized: view
    silver:
      +materialized: incremental
    gold:
      +materialized: table
